server:
  port: 8080

#Datasource 数据库配置
spring:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      druid:
        first:  #数据源1
          url: jdbc:mysql://47.111.9.173:3306/elasticjob?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          username: root
          password: root
        initial-size: 10
        max-active: 100
        min-idle: 10
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1 FROM dual
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        stat-view-servlet:
          enabled: true
          url-pattern: /druid/*
          #login-username: admin
          #login-password: admin
        filter:
          stat:
            log-slow-sql: true
            slow-sql-millis: 1000
            merge-sql: true
          wall:
            config:
              multi-statement-allow: true


regCenter:
  serverList: 127.0.0.1:2181
  namespace: oneface-job-test
jobs:
  testjob:
    name: synstestelastic
    cron: "*/5 * * * * ?"
    shardingCount: 1
    shardingItemParameters: 0=A
    description: 测试
